# dist: bionic

matrix:
  include:
    - language: python
      python: 3.8
      install: pip install pytz attrs .
      script: cd tests && python -E -Wall -tt -bb test_serpent.py

    - language: python
      python: 3.7
      install: pip install pytz attrs .
      script: cd tests && python -E -Wall -tt -bb test_serpent.py

    - language: python
      python: 3.6
      install: pip install pytz attrs .
      script: cd tests && python -E -Wall -tt -bb test_serpent.py

    - language: python
      python: 3.5
      install: pip install pytz attrs .
      script: cd tests && python -E -Wall -tt -bb test_serpent.py

    - language: python
      python: pypy3
      install: pip install pytz attrs .
      script: cd tests && python -E -Wall -bb test_serpent.py

    - language: java
      # jdk:
      #  - oraclejdk8
      script: mvn -f java/pom.xml verify
      cache:
        directories:
          - '$HOME/.m2/repository'

    - language: csharp
      dotnet: 2.2
      mono: none
      script:
       - dotnet restore
       - dotnet test dotnet/Serpent/Tests
